// Generated by gencpp from file simulator/GameStateResponse.msg
// DO NOT EDIT!


#ifndef SIMULATOR_MESSAGE_GAMESTATERESPONSE_H
#define SIMULATOR_MESSAGE_GAMESTATERESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace simulator
{
template <class ContainerAllocator>
struct GameStateResponse_
{
  typedef GameStateResponse_<ContainerAllocator> Type;

  GameStateResponse_()
    : received(false)  {
    }
  GameStateResponse_(const ContainerAllocator& _alloc)
    : received(false)  {
  (void)_alloc;
    }



   typedef uint8_t _received_type;
  _received_type received;





  typedef boost::shared_ptr< ::simulator::GameStateResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::simulator::GameStateResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GameStateResponse_

typedef ::simulator::GameStateResponse_<std::allocator<void> > GameStateResponse;

typedef boost::shared_ptr< ::simulator::GameStateResponse > GameStateResponsePtr;
typedef boost::shared_ptr< ::simulator::GameStateResponse const> GameStateResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::simulator::GameStateResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::simulator::GameStateResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::simulator::GameStateResponse_<ContainerAllocator1> & lhs, const ::simulator::GameStateResponse_<ContainerAllocator2> & rhs)
{
  return lhs.received == rhs.received;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::simulator::GameStateResponse_<ContainerAllocator1> & lhs, const ::simulator::GameStateResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace simulator

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::simulator::GameStateResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::simulator::GameStateResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::simulator::GameStateResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::simulator::GameStateResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::simulator::GameStateResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::simulator::GameStateResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::simulator::GameStateResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dd4152e077925db952c78baadb1e48b7";
  }

  static const char* value(const ::simulator::GameStateResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xdd4152e077925db9ULL;
  static const uint64_t static_value2 = 0x52c78baadb1e48b7ULL;
};

template<class ContainerAllocator>
struct DataType< ::simulator::GameStateResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "simulator/GameStateResponse";
  }

  static const char* value(const ::simulator::GameStateResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::simulator::GameStateResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool received\n"
"\n"
;
  }

  static const char* value(const ::simulator::GameStateResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::simulator::GameStateResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.received);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GameStateResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::simulator::GameStateResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::simulator::GameStateResponse_<ContainerAllocator>& v)
  {
    s << indent << "received: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.received);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SIMULATOR_MESSAGE_GAMESTATERESPONSE_H
